name: Gradle Release

on:
  push:
    branches:
    - master
    tags:
    - '*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Set env
      run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})
    - name: Debug Bintray environment variable
      run: echo BINTRAY_USER=$BINTRAY_USER
    - name: Build with Gradle
      run: ./gradlew -Pversion=$RELEASE_VERSION release --scan --no-daemon -i
